### ISSUE TITLE
Unable to finish ./build.sh

### ISSUE THREAD

**Issue by yizhouzhao** [isaac-sim/IsaacSim#1]
Hi experts,

I tried to build Isaac Sim but I encountered several errors:

```
  +++ |+#include <cstdint>
   26 | #endif
../../../source/extensions/isaacsim.core.includes/include/isaacsim/core/includes/core/Platform.h:104:7: error: ‘uint32_t’ does not name a type
  104 | const uint32_t kMaxPathLength = 2048;
```

And

```
/usr/include/stdlib.h(141): error: identifier "_Float32" is undefined
```

What is the GCC/G++ verion required to compile?

Here is my current system:
RTX A6000, Ubuntu 24.04, Driver 550,

**Comment by renanmb** [comment]
the first error of Isaac 5.0. I see 2 potential issues Ubuntu 24.04 and Driver 550. This might not be related to the problem but might bite you back depending on what you are trying to run.

**Comment by sheikh-nv** [comment]
I can repro the error on Ubuntu 24.04. Current tests have been on Ubuntu 22.04.
We will look into a fix. Thanks for reporting this issue!

**Comment by singh-jayant** [comment]
@traversaro presented a nice solution but it doesn't work for me so I am posting a docker based builder that should work on Ubuntu 24.04. 

###
My Setup:
- GPU: GeForce RTX 5070 Ti
- OS: Ubuntu 24.04, Kernel: 6.11.0-26-generic
- AMD Ryzen 5 8400F 6-Core Processor
- 64 GB Memory

## Overview

Building Isaac Sim 5.0.0 directly on Ubuntu 24.04 presents C++17 compatibility issues that cause build failures even after fixing the `cstdint` include in `Platform.h`. This guide provides a Docker-based solution that successfully builds Isaac Sim while handling symlinks and compatibility issues.

## Prerequisites

- Docker and Docker Compose installed
- NVIDIA Docker runtime configured
- NVIDIA GPU with CUDA support

## Solution: Docker-based Build

### Step 1: Create Docker Compose Configuration

Create a `docker-compose.yml` file in your Isaac Sim source directory:

````yaml
version: '3.8'

services:
  isaacsim-builder:
    image: nvidia/cuda:12.9.0-cudnn-devel-ubuntu22.04
    container_name: isaacsim_builder
    working_dir: /isaacsim
    volumes:
      - ./:/isaacsim
    command: "/bin/bash"
    stdin_open: true
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
````

### Step 2: Start the Build Container

Launch the Docker container:

```bash
docker compose up
```

### Step 3: Prepare Build Environment

Inside the container, install required dependencies and start the build:

```bash
apt update && apt install -y curl rsync
./build.sh -r
```

### Step 4: Extract Build Artifacts and collect all symlinks

Use `rsync` with the `-L` flag to resolve symlinks and copy the build output:

```bash
rsync -avL ./_build/linux-x86_64/release/ ./isaacsim-release/
```

### Step 5: Fix Permissions

After exiting the container, fix file ownership on the host (docker container user is root):

```bash
sudo chown $USER:$USER -R ./isaacsim-release
```

### Step 6: Install PyTorch Dependencies

Install the nightly torch packages (the stable 2.7.X does not work for me):

```bash
./python.sh -m pip install --upgrade --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
```

### Step 7: Verify Installation

Run the test suite to verify the build:

```bash
./run_all_tests.py
```

## Key Points

- **Ubuntu 22.04 base image**: Uses CUDA 12.9.0 with cuDNN on Ubuntu 22.04 to avoid C++17 compatibility issues
- **Symlink resolution**: The `rsync -avL` command resolves symlinks during the copy operation
- **Permission management**: Docker creates files as root, requiring ownership changes on the host
- **PyTorch compatibility**: Uses nightly CUDA 12.8 builds for compatibility

## Why This Works

1. **Containerized environment**: Isolates the build from Ubuntu 24.04 host issues
2. **Symlink handling**: `rsync -L` follows symlinks and copies actual files
3. **NVIDIA runtime**: Provides GPU access for CUDA-dependent components
4. **Clean extraction**: Creates a portable Isaac Sim installation directory

This approach successfully builds Isaac Sim 5.0.0 and produces a working installation that can be used on Ubuntu 24.04 systems.


I'm still facing some errors here and there but so far simulations seem to work
```sh
2025-06-16T00:16:55Z [7,897ms] [Error] [omni.kit.renderer.plugin] IRendererImpl::updateReferenceFromTextureData getResourcesDescriptorSet failed for pool 1
```

**Comment by byeongkyu** [comment]
Just alternative install gcc-12, g++-12.
And, select it default gcc, g++.

```
$ sudo apt install gcc-12 g++-12

$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 30
$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 30

$ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 30
$ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 30

$ sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
$ sudo update-alternatives --set cc /usr/bin/gcc

$ sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
$ sudo update-alternatives --set c++ /usr/bin/g++
```

```
$ sudo update-alternatives --config gcc
$ sudo update-alternatives --config g++
```

And, rebuild isaacsim
```
$ ./build.sh -x
```

**Comment by traversaro** [comment]
A slight variant of @byeongkyu is to use environment variables to avoid changing the global system state via `update-alternatives`, i.e. : 

~~~
sudo apt install gcc-12 g++-12
export CUDAHOSTCXX=/usr/bin/g++-12; export CC=gcc-12; export CXX=g++-12
./build.sh
~~~

should also work fine.

**Comment by hmazhar-nv** [comment]
GCC 12 on Ubuntu 24 may still have some issues when running isaac sim. Namely this error
`NumPy type info missing for N4carb6Float3E`

Using GCC/G++ 11 is recommended to get past this issue

```
sudo apt-get install gcc-11 g++-11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 200
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 200
```
